import { 
  MessageSquare, 
  Puzzle, 
  Database, 
  Variable as VariableIcon, 
  GitBranch, 
  Book, 
  Bot, 
  StickyNote, 
  Network, 
  Download,
  Upload,
  Zap,
  Settings,
  FileText,
  Code,
  Cpu,
  Globe,
  Send,
  RefreshCw,
  Filter,
  Layers,
  Box,
  Sparkles,
  Wand2,
  Workflow,
  LayoutGrid,
  Target,
  Lightbulb,
  Shapes,
  Plug,
  // Data & Files
  FileJson,
  FileSpreadsheet,
  FolderOpen,
  Archive,
  Clipboard,
  ClipboardList,
  Table,
  FileCog,
  // AI & Processing
  Brain,
  Cog,
  CircuitBoard,
  Binary,
  Braces,
  Hash,
  Sigma,
  // Communication
  Mail,
  MessageCircle,
  BellRing,
  Megaphone,
  Radio,
  // Visual & Charts
  BarChart,
  LineChart,
  PieChart,
  TrendingUp,
  Activity,
  // Actions
  Play,
  Pause,
  Check,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  // Connections
  Link,
  Unlink,
  Share2,
  ArrowRightLeft,
  Repeat,
  Shuffle,
  // Objects
  Clock,
  Calendar,
  MapPin,
  Tag,
  Bookmark,
  Star,
  Heart,
  Flag,
  // Structure
  Folder,
  List,
  ListChecks,
  TreePine,
  Boxes,
  Package,
  type LucideIcon
} from 'lucide-react';

export interface PaletteItem {
  type: string;
  icon: LucideIcon;
  title: string;
  description: string;
  category: 'transform' | 'design' | 'connect';
  disabled?: boolean;
  comingSoon?: boolean;
}

export interface NodeCustomization {
  title?: string;
  description?: string;
  enabled?: boolean;
  icon?: string;
  category?: 'transform' | 'design' | 'connect';
}

export type NodeCustomizations = Record<string, NodeCustomization>;

// Icon registry for dynamic icon lookup
export const iconRegistry: Record<string, LucideIcon> = {
  MessageSquare,
  Puzzle,
  Database,
  Variable: VariableIcon,
  GitBranch,
  Book,
  Bot,
  StickyNote,
  Network,
  Download,
  Upload,
  Zap,
  Settings,
  FileText,
  Code,
  Cpu,
  Globe,
  Send,
  RefreshCw,
  Filter,
  Layers,
  Box,
  Sparkles,
  Wand2,
  Workflow,
  LayoutGrid,
  Target,
  Lightbulb,
  Shapes,
  Plug,
  // Data & Files
  FileJson,
  FileSpreadsheet,
  FolderOpen,
  Archive,
  Clipboard,
  ClipboardList,
  Table,
  FileCog,
  // AI & Processing
  Brain,
  Cog,
  CircuitBoard,
  Binary,
  Braces,
  Hash,
  Sigma,
  // Communication
  Mail,
  MessageCircle,
  BellRing,
  Megaphone,
  Radio,
  // Visual & Charts
  BarChart,
  LineChart,
  PieChart,
  TrendingUp,
  Activity,
  // Actions
  Play,
  Pause,
  Check,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  // Connections
  Link,
  Unlink,
  Share2,
  ArrowRightLeft,
  Repeat,
  Shuffle,
  // Objects
  Clock,
  Calendar,
  MapPin,
  Tag,
  Bookmark,
  Star,
  Heart,
  Flag,
  // Structure
  Folder,
  List,
  ListChecks,
  TreePine,
  Boxes,
  Package,
};

// Available icons for the picker (curated list)
export const iconOptions = [
  // Original icons
  { name: 'MessageSquare', label: 'Message' },
  { name: 'Puzzle', label: 'Puzzle' },
  { name: 'Database', label: 'Database' },
  { name: 'Variable', label: 'Variable' },
  { name: 'GitBranch', label: 'Branch' },
  { name: 'Book', label: 'Book' },
  { name: 'Bot', label: 'Bot' },
  { name: 'StickyNote', label: 'Note' },
  { name: 'Network', label: 'Network' },
  { name: 'Download', label: 'Download' },
  { name: 'Upload', label: 'Upload' },
  { name: 'Zap', label: 'Zap' },
  { name: 'Settings', label: 'Settings' },
  { name: 'FileText', label: 'File' },
  { name: 'Code', label: 'Code' },
  { name: 'Cpu', label: 'CPU' },
  { name: 'Globe', label: 'Globe' },
  { name: 'Send', label: 'Send' },
  { name: 'RefreshCw', label: 'Refresh' },
  { name: 'Filter', label: 'Filter' },
  { name: 'Layers', label: 'Layers' },
  { name: 'Box', label: 'Box' },
  { name: 'Sparkles', label: 'Sparkles' },
  { name: 'Wand2', label: 'Wand' },
  { name: 'Workflow', label: 'Workflow' },
  { name: 'LayoutGrid', label: 'Grid' },
  { name: 'Target', label: 'Target' },
  { name: 'Lightbulb', label: 'Idea' },
  { name: 'Shapes', label: 'Shapes' },
  { name: 'Plug', label: 'Plug' },
  // Data & Files
  { name: 'FileJson', label: 'JSON' },
  { name: 'FileSpreadsheet', label: 'Spreadsheet' },
  { name: 'FolderOpen', label: 'Folder Open' },
  { name: 'Archive', label: 'Archive' },
  { name: 'Clipboard', label: 'Clipboard' },
  { name: 'ClipboardList', label: 'Checklist' },
  { name: 'Table', label: 'Table' },
  { name: 'FileCog', label: 'Config' },
  // AI & Processing
  { name: 'Brain', label: 'Brain' },
  { name: 'Cog', label: 'Cog' },
  { name: 'CircuitBoard', label: 'Circuit' },
  { name: 'Binary', label: 'Binary' },
  { name: 'Braces', label: 'Braces' },
  { name: 'Hash', label: 'Hash' },
  { name: 'Sigma', label: 'Sigma' },
  // Communication
  { name: 'Mail', label: 'Mail' },
  { name: 'MessageCircle', label: 'Chat' },
  { name: 'BellRing', label: 'Alert' },
  { name: 'Megaphone', label: 'Announce' },
  { name: 'Radio', label: 'Radio' },
  // Visual & Charts
  { name: 'BarChart', label: 'Bar Chart' },
  { name: 'LineChart', label: 'Line Chart' },
  { name: 'PieChart', label: 'Pie Chart' },
  { name: 'TrendingUp', label: 'Trending' },
  { name: 'Activity', label: 'Activity' },
  // Actions
  { name: 'Play', label: 'Play' },
  { name: 'Pause', label: 'Pause' },
  { name: 'Check', label: 'Check' },
  { name: 'CheckCircle', label: 'Success' },
  { name: 'AlertCircle', label: 'Error' },
  { name: 'AlertTriangle', label: 'Warning' },
  { name: 'Info', label: 'Info' },
  { name: 'HelpCircle', label: 'Help' },
  // Connections
  { name: 'Link', label: 'Link' },
  { name: 'Unlink', label: 'Unlink' },
  { name: 'Share2', label: 'Share' },
  { name: 'ArrowRightLeft', label: 'Exchange' },
  { name: 'Repeat', label: 'Repeat' },
  { name: 'Shuffle', label: 'Shuffle' },
  // Objects
  { name: 'Clock', label: 'Clock' },
  { name: 'Calendar', label: 'Calendar' },
  { name: 'MapPin', label: 'Location' },
  { name: 'Tag', label: 'Tag' },
  { name: 'Bookmark', label: 'Bookmark' },
  { name: 'Star', label: 'Star' },
  { name: 'Heart', label: 'Heart' },
  { name: 'Flag', label: 'Flag' },
  // Structure
  { name: 'Folder', label: 'Folder' },
  { name: 'List', label: 'List' },
  { name: 'ListChecks', label: 'Tasks' },
  { name: 'TreePine', label: 'Tree' },
  { name: 'Boxes', label: 'Boxes' },
  { name: 'Package', label: 'Package' },
];

// Default icon names for each node type
export const defaultIconNames: Record<string, string> = {
  promptTemplate: 'MessageSquare',
  promptPiece: 'Puzzle',
  ingest: 'Download',
  dataset: 'Database',
  variable: 'Variable',
  framework: 'Book',
  agent: 'Bot',
  note: 'StickyNote',
  workflow: 'Network',
  condition: 'GitBranch',
  integration: 'Plug',
};

export const defaultPaletteItems: PaletteItem[] = [
  {
    type: 'promptTemplate',
    icon: MessageSquare,
    title: 'Generate',
    description: 'Use AI Model',
    category: 'transform',
  },
  {
    type: 'promptPiece',
    icon: Puzzle,
    title: 'Component',
    description: 'Add reusable component',
    category: 'transform',
  },
  {
    type: 'ingest',
    icon: Download,
    title: 'Ingest',
    description: 'Receive new data submissions',
    category: 'transform',
  },
  {
    type: 'dataset',
    icon: Database,
    title: 'Dataset',
    description: 'Reference data collections',
    category: 'transform',
  },
  {
    type: 'variable',
    icon: VariableIcon,
    title: 'Transformation',
    description: 'Transform data',
    category: 'transform',
  },
  {
    type: 'framework',
    icon: Book,
    title: 'Framework',
    description: 'Reference data model/schema',
    category: 'transform',
  },
  {
    type: 'agent',
    icon: Bot,
    title: 'SSOT Mapping',
    description: 'Map AI output to SSOT structure',
    category: 'transform',
  },
  {
    type: 'note',
    icon: StickyNote,
    title: 'Note',
    description: 'Add organizational text or title',
    category: 'design',
  },
  {
    type: 'workflow',
    icon: Network,
    title: 'Workflow',
    description: 'Reference another workflow',
    category: 'design',
  },
  {
    type: 'condition',
    icon: GitBranch,
    title: 'Automate',
    description: 'Automation functions',
    category: 'connect',
  },
  {
    type: 'integration',
    icon: Plug,
    title: 'Integration',
    description: 'Call external APIs',
    category: 'connect',
  },
];
